### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**
### Description

Create pt.json

### Types of changes

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to change)
- [ ] **Enhancement** (changes that improvement of current feature or performance)
- [ ] **Refactoring** (changes that neither fixes a bug nor adds a feature)
- [ ] **Code style optimization** (changes that do not affect the meaning of the code)
- [ ] **Docs** (changes that only update documentation)
- [ ] **Chore** (changes that don't modify src or test files)

### Self Check before Merge

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Review by geertmeersman — CHANGES_REQUESTED** [review]
Shouldn't senha start with a capital?
And like 34, before mijn miwa there are 2 spaces.

Thanks!

**Comment by ViPeR5000** [comment]
> Shouldn't senha start with a capital? And like 34, before mijn miwa there are 2 spaces.
> 
> Thanks!

Ups :)

Fixed

**Review by geertmeersman — CHANGES_REQUESTED** [review]
Line 46 & 43 😀

**Review by geertmeersman — COMMENTED** [review]
👍

**Pull request merged**
